version: '3'
services:
  app:
    container_name: sustainability-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "9999:9999"
    volumes:
      - .:/opt/www
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    container_name: sustainability-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3308:3306"
  redis:
    container_name: sustainability-redis
    image: redis:6.2
    ports:
      - "6379:6379"
  mailhog:
    container_name: sustainability-mail
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - "8025:8025"
      - "1025:1025"
networks:
  sustainability:
    driver: bridge